### ISSUE TITLE
No Screen Recordings Show Up

### ISSUE THREAD

**Issue by dima-gusyatiner** [kolkov/ngx-metrika#5]
When using this package,
I don't get any screen recordings in Yandex Metrika dashboard.

I didn't have time to get into this too much (and couldn't because #3),
but when using [ng-yandex-metrika](https://github.com/FriOne/ng-yandex-metrika), screen recordings do show up.

Can you investigate this?

**Comment by dima-gusyatiner** [comment]
Sorry, my bad.
You need to set [`webvisor` to `true`](https://yandex.com/support/metrica/code/counter-initialize.html#counter-initialize__param-webvisor), when importing this library (in `forRoot`).

**Comment by kolkov** [comment]
Hi! Thanks for your feedback.
